// apps/react-book/src/components/NavBar.tsx
import { NavLink } from 'react-router-dom'
import { useInput } from 'rooks'
import { routes } from '../routes'

export const NavBar = () => {
  const search = useInput('')
  const menuList = routes.map((item) => item.path)
  let showMenuList = menuList
  if (search.value !== '') {
    showMenuList = menuList.filter((menu) => menu.includes(search.value))
  }
  return (
    <aside className="bg-base-200 w-80 p-4">
      <a className="btn btn-ghost normal-case text-xl">React-UI</a>
      <input
        type="text"
        placeholder="Search..."
        className="input w-full max-w-xs"
        {...search}
      />
      <ul className="menu mt-4">
        {showMenuList.map((menu) => (
          <li className="w-full" key={menu}>
            <NavLink to={menu}>{menu}</NavLink>
          </li>
        ))}
      </ul>
    </aside>
  )
}

// apps/vue-book/src/components/nav-bar.vue
<template>
  <aside class="bg-base-200 w-80 p-4">
    <a class="btn btn-ghost normal-case text-xl">Vue-UI</a>
    <input
      type="text"
      placeholder="Search..."
      class="input w-full max-w-xs"
      v-model="search"
    />
    <ul class="menu mt-4">
      <li class="w-full" v-for="menu of showMenuList" :key="menu">
        <router-link :activeClass="'active'" :to="menu">
          {{ menu.slice(1) }}
        </router-link>
      </li>
    </ul>
  </aside>
</template>

<script lang="ts" setup>
import { computed, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { routes } from '../routes'

const menuList = routes.map((item) => item.path)
const search = ref('')

const showMenuList = computed(() => {
  if (search.value === '') {
    return menuList
  } else {
    return menuList.filter((menu) => menu.includes(search.value))
  }
})
</script>

<style>
/*.bordered{*/
/*  border-left: 2px solid;*/
/*}*/
</style>
