// apps/vue-book/src/App.vue
<template>
  <div class="content">
    <nav-bar />
    <div
      class="p-16"
      style="scroll-behavior: smooth; scroll-padding-top: 5rem; flex: 1"
    >
      <div class="prose w-full max-w-4xl flex-grow">
        <h1 class="text-xl mb-8">组件示例</h1>
        <router-view />
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { RouterView } from 'vue-router'
import NavBar from './components/nav-bar.vue'
</script>

<style>
.content {
  display: flex;
  height: 100vh;
  width: 100vw;
}

pre,
code {
  height: 200px;
}
</style>

// apps/react-book/src/App.tsx
import { Suspense } from 'react'
import { Routes, Route } from 'react-router-dom'
import './App.css'
import { NavBar } from './components/NavBar'
import { routes } from './routes'

function App() {
  return (
    <div className="App">
      <NavBar />
      <div
        className="p-16"
        style={{ scrollBehavior: 'smooth', scrollPaddingTop: '5rem', flex: 1 }}
      >
        <div className="prose w-full max-w-4xl flex-grow">
          <h1 className="text-xl mb-8">组件示例</h1>
          <Suspense fallback={<>...</>}>
            <Routes>
              {routes.map(({ path, Page }) => {
                return <Route path={path} key={path} element={<Page />} />
              })}
            </Routes>
          </Suspense>
        </div>
      </div>
    </div>
  )
}

export default App
